version: 2.1

jobs:
  explore:
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_REGION: ap-northeast-1
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: check credentials
          command: |
            aws sts get-caller-identity

workflows:
  main:
    jobs:
      - explore
