version: 2.1

jobs:
  explore:
    environment:
      AWS_ACCESS_KEY_ID: hogehoge
    docker:
      - image: circleci/golang:1.15
    steps:
      - run:
          name: 環境変数を確認する
          command: |
            printenv AWS_ACCESS_KEY_ID
      - run:
          name: 環境変数を変更してみる
          # こちらのシェールセッションには、AWS_ACCESS_KEY_ID 環境変数が変更された。
          command: |
            export AWS_ACCESS_KEY_ID=foobar
            printenv AWS_ACCESS_KEY_ID
      - run:
          name: 環境変数を確認する
          # ただ、次のステップは新しいシェールセッションでコマンドを実行する。
          # このため、AWS_ACCESS_KEY_ID が hogehoge になります。
          command: |
            printenv AWS_ACCESS_KEY_ID
      - run:
          name: 環境変数を次のステップにも新しい値を利用できるため
          # BASH_ENV ファイルが全てのスッテプで読まれる。
          command: |
            echo 'export AWS_ACCESS_KEY_ID=foobar' >> $BASH_ENV
            printenv AWS_ACCESS_KEY_ID
      - run:
          name: 環境変数を確認する
          command: |
            printenv AWS_ACCESS_KEY_ID

workflows:
  main:
    jobs:
      - explore
