version: 2.1

jobs:
  explore-params:
    environment:
      DOCKER_MAIN_IMAGE: cimg/base:stable
    parameters:
      foo:
        type: env_var_name
        default: FOO
      bar:
        type: string
        default: $BAR
      docker-image:
        type: env_var_name
        default: DOCKER_MAIN_IMAGE
    docker:
      - image: $<< parameters.docker-image >>
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PERSONAL_ACCESS_TOKEN
    resource_class: small
    steps:
      - run:
          name: check << parameters.foo >> env var in various ways
          command: |
            echo $<< parameters.foo >>
            echo $FOO
          environment:
            FOO: fizz
      - run:
          name: check << parameters.bar >> string in various ways
          command: |
            echo << parameters.bar >>
            echo $BAR
          environment:
            BAR: buzz
  explore-workdir:
    environment:
      CUSTOM_WORKDIR_NAME: repo
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PERSONAL_ACCESS_TOKEN
    resource_class: small
    working_directory: $CUSTOM_WORKDIR_NAME
    steps:
      - run:
          name: check context
          command: |
            pwd
            ls -laH

workflows:
  envvars-are-fun:
    jobs:
      - explore-params
      - explore-workdir
